export const IMG_PATH = {
  BARK_BANK_LOGO: "/images/bark-bank-logo.svg",
  CHECK_MAIL: "/images/check-mail.svg",
  CONTACT_US: "/images/contact-us.svg",
  EMAIL: "/images/email.svg",
  ORANGE_DOG_HOUSE: "/images/orange-dog-house.svg",
  PAW_PRINT: "/images/pawPrint.svg",
  PURPLE_DOG_HOUSE: "/images/purpleDogHouse.svg",
  SIDEBAR_DASHBOARD_LIGHT: "/images/dashboard-light.svg",
  SIDEBAR_DASHBOARD: "/images/dashboard.svg",
  SIDEBAR_DATABASE_LIGHT: "/images/database-light.svg",
  SIDEBAR_DATABASE: "/images/database.svg",
  SIDEBAR_KEY_LIGHT: "/images/key-light.svg",
  SIDEBAR_KEY: "/images/key.svg",
  SIDEBAR_SQUARE_LIGHT: "/images/square-light.svg",
  SIDEBAR_SQUARE: "/images/square.svg",
} as const;
